### ISSUE TITLE
新建用户保存的时候出错

### ISSUE THREAD

**Issue by NecoraNyaru** [chaegumi/cxpcms#3]
进入Users->Add User，输入数据会出错。users_edit.save()方法没有办法被访问到。
<img width="1280" alt="2016-12-01 7 02 24" src="https://cloud.githubusercontent.com/assets/14267128/20775177/a23ecd18-b794-11e6-8f32-14d0514edf78.png">
如果可以的话请帮忙看一下，谢谢！

**Comment by chaegumi** [comment]
这种错误，开network那个选项卡调试，不是看console选项卡。

**Comment by chaegumi** [comment]
我试了下，添加没错，你先自己调试下。

**Comment by NecoraNyaru** [comment]
开到network看出错误了。。。是新手刚接触这个。。对不起打扰到您了
